"""Round-2 independent verification of M5 industry momentum: checks every number changed or added by the builder's
fixes to the round-1 required fixes.

Does NOT import module code (run.py, m5lib.py, optimizer.py, team_replica.py). Uses lib/common.py loaders,
lib/team_pipeline.py (orchestrator's tested team replica, for the Short-Brown series and the attention-lag variant),
the round-1 verifier helpers in verify/vlib.py, and verify/verify_opt_path_X_unc.csv (the round-1 verifier's OWN
optimizer path, regenerated by verify_m5_optimizer.py). Bootstrap seeds differ from the builder's.

Run:  cd /home/hashim/projects/GA/project/research && uv run python modules/M5_industry_momentum/verify/verify_m5_round2.py
Writes verify/verify_round2_results.csv.
"""
from __future__ import annotations
import sys, pathlib
import numpy as np
import pandas as pd
from scipy import stats

RES = pathlib.Path("/home/hashim/projects/GA/project/research")
sys.path.insert(0, str(RES / "lib"))
import common as C  # noqa: E402
OUT = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))
from vlib import nw, ann, cbb, sr, book, S, R, R_kf, F5, F3, X6, MODELS, cap, emis, T, tab  # noqa: E402

rows = []
def chk(item, claim, builder, mine, tol, csv=None, note=""):
    ok = abs(float(mine) - float(builder)) <= tol + 1e-12
    csv_s = "" if csv is None else f"{float(csv):.6g}"
    rows.append({"item": item, "claim": claim, "builder": builder, "mine": float(mine), "csv": csv_s, "tol": tol,
                 "verdict": "confirmed" if ok else "DISCREPANCY", "note": note})
    print(f"{'confirmed' if ok else 'DISCREPANCY':12s} [{item}] {claim:62s} builder {builder!s:>9} mine {float(mine):11.5f} csv {csv_s:>10} {note}")

def flag(item, claim, ok, note=""):
    rows.append({"item": item, "claim": claim, "builder": "", "mine": np.nan, "csv": "", "tol": np.nan,
                 "verdict": "confirmed" if ok else "DISCREPANCY", "note": note})
    print(f"{'confirmed' if ok else 'DISCREPANCY':12s} [{item}] {claim:62s} {note}")

def ols_classic(y, X):
    """Classic OLS intercept t with Student-t p on n-k df (own)."""
    d = pd.concat([pd.Series(y).rename("__y"), pd.DataFrame(X)], axis=1).dropna()
    Y = d["__y"].values; Xm = np.column_stack([np.ones(len(d)), d.drop(columns="__y").values])
    b, *_ = np.linalg.lstsq(Xm, Y, rcond=None); u = Y - Xm @ b; dof = len(Y) - Xm.shape[1]
    s2 = u @ u / dof; se = np.sqrt(np.diag(s2 * np.linalg.inv(Xm.T @ Xm)))
    t = b[0] / se[0]; return t, 2 * stats.t.sf(abs(t), dof), dof

def boot2(a, b, seed, B=5000, block=12):
    d = pd.concat([a, b], axis=1).dropna(); A, Bv = d.iloc[:, 0].values, d.iloc[:, 1].values
    ix = cbb(len(d), block, B, np.random.default_rng(seed))
    hat = sr(A) - sr(Bv); st = sr(A[ix], 1) - sr(Bv[ix], 1)
    return hat, np.percentile(st, 2.5), np.percentile(st, 97.5), float(np.mean(np.abs(st - hat) >= abs(hat)))

bt, Wh = book(R)
INDMOM = bt["gross"].rename("INDMOM")

# ============================== item 2 (builder 1): GB HML attribution
green, brown = C.legs_by_emissions(5)
GB = (T["industries"][green].mean(axis=1) - T["industries"][brown].mean(axis=1)).rename("GB")
F = F3[["Mkt-RF", "SMB", "HML"]].join(INDMOM).join(F5["UMD"])
for p, vals in {"full": [(-0.233, -4.63), (-0.253, -5.27), (-0.256, -5.20)], "post2010": [(-0.298, -5.74), (-0.306, -5.76), (-0.323, -6.16)]}.items():
    y = S(GB, p)
    for (bb, bt_), spec in zip(vals, (["Mkt-RF", "SMB", "HML"], ["Mkt-RF", "SMB", "HML", "INDMOM"], ["Mkt-RF", "SMB", "HML", "UMD"])):
        r = nw(y, F.loc[y.index, spec])
        chk("R1-2", f"GB HML {p} {'+'.join(spec[3:]) or 'FF3'}", bb, r["b"]["HML"], 0.0005)
        chk("R1-2", f"GB HML t {p} {'+'.join(spec[3:]) or 'FF3'}", bt_, r["t"]["HML"], 0.005)

# ============================== item 3 (builder 2): holdout alphas of variants; 6-1 classic OLS
VAR = {"primary": dict(), "1-0": dict(L=1, Skip=0), "6-1": dict(L=6, Skip=1), "12-1": dict(L=12, Skip=1), "12-0": dict(L=12, Skip=0),
       "n5": dict(n=5), "n10": dict(n=10), "capw": dict(capdf=cap)}
hold = {}
for k, kw in VAR.items():
    b_, _ = book(R, **kw); rh = nw(S(b_["net"], "holdout"), X6); hold[k] = (1200 * rh["b"]["const"], rh["t"]["const"], b_)
b_kf, W_kf = book(R_kf); rh = nw(S(b_kf["net"], "holdout"), X6); hold["kf"] = (1200 * rh["b"]["const"], rh["t"]["const"], b_kf)
kmin = min(hold, key=lambda k: hold[k][0]); kt = min(hold, key=lambda k: hold[k][1])
flag("R1-3", "all 9 holdout alphas negative", all(v[0] < 0 for v in hold.values()), "; ".join(f"{k}:{v[0]:.2f}({v[1]:.2f})" for k, v in hold.items()))
flag("R1-3", "lowest holdout alpha = cap-weighted; most negative t = 6-1", kmin == "capw" and kt == "6-1", f"min alpha {kmin}, min t {kt}")
chk("R1-3", "capw holdout alpha (%)", -13.33, hold["capw"][0], 0.005); chk("R1-3", "capw holdout t", -2.16, hold["capw"][1], 0.005)
chk("R1-3", "6-1 holdout alpha (%)", -10.79, hold["6-1"][0], 0.005); chk("R1-3", "6-1 holdout t", -3.02, hold["6-1"][1], 0.005)
t61, p61, _ = ols_classic(S(hold["6-1"][2]["net"], "holdout"), X6.loc[S(hold["6-1"][2]["net"], "holdout").index])
chk("R1-3", "6-1 holdout classic OLS t", -1.61, t61, 0.005); chk("R1-3", "6-1 holdout Student-t p", 0.116, p61, 0.0005)

# ============================== item 7 (builder 6): KF vintage
D = (R_kf - R).loc["1926-07-31":"2026-07-31"]
cells = (D.abs() > 1e-9); mdiff = cells.any(axis=1)
chk("R1-7", "cells differing", 113, int(cells.values.sum()), 0); chk("R1-7", "months differing", 54, int(mdiff.sum()), 0)
flag("R1-7", "first differing month 2020-07", f"{mdiff[mdiff].index[0]:%Y-%m}" == "2020-07", f"{mdiff[mdiff].index[0]:%Y-%m}")
chk("R1-7", "max |diff| outside 2026-07 (pp)", 0.22, 100 * D.drop(pd.Timestamp("2026-07-31")).abs().max().max(), 0.005)
last = D.loc["2026-07-31"]
chk("R1-7", "2026-07 industries differing", 26, int((last.abs() > 1e-9).sum()), 0)
chk("R1-7", "2026-07 max |diff| (pp), PerSv", 7.02, 100 * last.abs().max(), 0.005, note=str(last.abs().idxmax()))
big = sorted(last[last.abs() > 0.01].index); short_jul = sorted(Wh.loc["2026-07-31"][Wh.loc["2026-07-31"] < 0].index)
flag("R1-7", ">1pp movers are PerSv, Clths, BusSv, all in 2026-07 short leg", big == sorted(["PerSv", "Clths", "BusSv"]) and set(big) <= set(short_jul), f"movers {big}; short leg {short_jul}")
flag("R1-7", "weights identical under KF vintage in every month", bool(np.allclose(W_kf.values, Wh.values)), f"max |dw| {np.abs(W_kf.values - Wh.values).max():.2e}")
chk("R1-7", "2026-07 net under KF (%)", -13.95, 100 * b_kf.loc["2026-07-31", "net"], 0.005)
chk("R1-7", "2026-07 net under team (%)", -14.18, 100 * bt.loc["2026-07-31", "net"], 0.005)
chk("R1-7", "2026-07 rank among worst under KF", 6, int((b_kf["net"] < b_kf.loc["2026-07-31", "net"]).sum() + 1), 0)

# ============================== item 6 (builder 5): COVID alpha and small-sample checks; decades
cv = S(bt["net"], "full").loc["2020-01-31":"2021-12-31"]
for mname, (ba, bt_, bols, bp) in {"FF5+UMD": (15.80, 3.18, 1.58, 0.132), "FF5": (None, 6.44, 1.99, 0.061), "FF3": (None, 3.03, 1.36, 0.189)}.items():
    r = nw(cv, MODELS[mname]); to, po, dof = ols_classic(cv, MODELS[mname].loc[cv.index])
    if ba is not None:
        chk("R1-6", f"COVID {mname} alpha (%)", ba, 1200 * r["b"]["const"], 0.005)
    chk("R1-6", f"COVID {mname} NW t", bt_, r["t"]["const"], 0.005)
    chk("R1-6", f"COVID {mname} classic OLS t (df {dof})", bols, to, 0.005, note=f"ratio NW/OLS {r['t']['const'] / to:.2f}")
    chk("R1-6", f"COVID {mname} Student-t p", bp, po, 0.0005)
dec = {"1970s": ("1970", "1979"), "1980s": ("1980", "1989"), "1990s": ("1990", "1999"), "2000s": ("2000", "2009"), "2010s": ("2010", "2019"), "2020s": ("2020", "2026-07")}
dres = {k: nw(bt["net"].loc[a:b], X6) for k, (a, b) in dec.items()}
chk("R1-6", "max |t| decade FF5+UMD alpha (1990s)", 1.80, max(abs(v["t"]["const"]) for v in dres.values()), 0.005)
chk("R1-6", "1990s FF5+UMD alpha (%)", 5.89, 1200 * dres["1990s"]["b"]["const"], 0.005)
others = {"full": S(bt["net"], "full"), "post2010": S(bt["net"], "post2010"), "validation": S(bt["net"], "validation"), "holdout": S(bt["net"], "holdout"),
          "pre_covid": bt["net"].loc["2010-01-31":"2019-12-31"], "inflation_rates": bt["net"].loc["2022-01-31":"2024-12-31"]}
alls = {k: 1200 * nw(v, X6)["b"]["const"] for k, v in others.items()} | {k: 1200 * v["b"]["const"] for k, v in dres.items()}
flag("R1-6", "next largest FF5+UMD alpha after COVID is 1990s 5.89%", max(alls, key=alls.get) == "1990s", str({k: round(v, 2) for k, v in alls.items()}))

# ============================== item 12a (builder 11a): holdout break-even
g, to = S(bt["gross"], "holdout"), S(bt["to"], "holdout")
ag = 1200 * nw(g, X6)["b"]["const"]
chk("R1-12a", "holdout gross FF5+UMD alpha (%)", -3.14, ag, 0.005)
chk("R1-12a", "holdout mean break-even (bp)", 24, 1e4 * g.mean() / to.mean(), 0.5)
cb = tab("cost_breakeven").set_index("period")
flag("R1-12a", "holdout alpha break-even is NaN in CSV", bool(np.isnan(cb.loc["holdout", "breakeven_bp_alpha_ff5umd"])), str(cb.loc["holdout", "breakeven_bp_alpha_ff5umd"]))

# ============================== items 4, 5 (builder 3, 4): optimizer periods from MY OWN optimizer path
u = pd.read_csv(OUT / "verify_opt_path_X_unc.csv", index_col=0, parse_dates=True)
rp = nw(S(u.net, "post2010"), X6)
chk("R1-5", "opt X_unc post-2010 alpha (%)", 3.12, 1200 * rp["b"]["const"], 0.01); chk("R1-5", "opt post-2010 t", 2.18, rp["t"]["const"], 0.01)
chk("R1-5", "opt post-2010 p", 0.029, rp["p"]["const"], 0.001); chk("R1-5", "opt post-2010 IR", 0.696, sr(S(u.net, "post2010").values), 0.001)
chk("R1-5", "EW primary post-2010 Sharpe", 0.43, sr(S(bt["net"], "post2010").values), 0.005)
rv = nw(S(u.net, "validation"), X6)
chk("R1-5", "opt validation alpha (%)", 2.99, 1200 * rv["b"]["const"], 0.01); chk("R1-5", "opt validation t", 1.78, rv["t"]["const"], 0.01)
hat, lo, hi, p = boot2(S(u.net, "post2010"), S(bt["net"], "post2010"), seed=31337)
chk("R1-5", "opt - EW post-2010 dIR", 0.267, hat, 0.002); chk("R1-5", "  CI lo (MC)", -0.111, lo, 0.03); chk("R1-5", "  CI hi (MC)", 0.657, hi, 0.03)
chk("R1-5", "  bootstrap p (own seed, MC)", 0.155, p, 0.03)
r20 = nw(u.net.loc["2020":"2026-07"], X6)
chk("R1-4", "opt 2020-2026 alpha (%)", 5.45, 1200 * r20["b"]["const"], 0.01); chk("R1-4", "opt 2020-2026 t", 1.97, r20["t"]["const"], 0.01)
chk("R1-4", "opt 2020-2026 p", 0.049, r20["p"]["const"], 0.001)
dts = {k: nw(u.net.loc[a:b], X6)["p"]["const"] for k, (a, b) in dec.items()}
flag("R1-4", "2020-2026 is the only decade with nominal p<0.05", [k for k, v in dts.items() if v < 0.05] == ["2020s"], str({k: round(v, 3) for k, v in dts.items()}))

# ============================== item 9 (builder 8): b=0 weak test, WACI level; post-2010 screens bootstrapped
b0 = pd.read_csv(OUT / "verify_opt_path_X_b+0.00.csv", index_col=0, parse_dates=True)
chk("R1-9a", "b=0 long WACI level", 0.141, b0.lwaci.mean(), 0.0015); chk("R1-9a", "b=0 long WACI cut (%)", -11.6, 100 * (b0.lwaci.mean() / u.lwaci.mean() - 1), 0.1)
chk("R1-9a", "b=0 binding share (%) (tolerance-sensitive)", 26.5, 100 * (b0.cz >= -1e-5).mean(), 0.3)
chk("R1-9a", "unconstrained mean c'h", -0.09, u.cz.mean(), 0.005)
covered = [c for c in R.columns if c in emis.index]
top8 = list(emis.sort_values(ascending=False).index[:8]); top5 = top8[:5]
allc = list(R.columns)
SCR = {"A0X": (covered, None), "A5X": ([c for c in covered if c not in top5], None), "A8X": ([c for c in covered if c not in top8], None),
       "B0X": (covered, covered), "B5X": ([c for c in covered if c not in top5],) * 2, "B8X": ([c for c in covered if c not in top8],) * 2,
       "A5M": ([c for c in allc if c not in top5], None), "A8M": ([c for c in allc if c not in top8], None),
       "B5M": ([c for c in allc if c not in top5],) * 2, "B8M": ([c for c in allc if c not in top8],) * 2}
BLD = {"B5X": (-0.120, -0.333, 0.081, 0.26), "B8X": (-0.110, -0.335, 0.105, 0.33), "A8X": (-0.036, None, None, 0.56),
       "A5M": (-0.067, -0.130, -0.010, 0.027), "B5M": (-0.117, -0.214, -0.026, 0.017), "B0X": (-0.071, None, None, 0.43)}
cs = tab("carbon_screens"); cs["k"] = cs.book.str.split("_").str[0]; cs = cs.set_index("k")
post, full_d, full_p = {}, {}, {}
for k, (lu, su) in SCR.items():
    b_, _ = book(R, long_u=lu, short_u=su)
    h_, l_, u_, p_ = boot2(S(b_["net"], "post2010"), S(bt["net"], "post2010"), seed=2718)
    hf, _, _, pf = boot2(b_["net"], bt["net"], seed=2718)
    post[k] = (h_, l_, u_, p_); full_d[k] = hf; full_p[k] = pf
    print(f"  {k}: post-2010 dSR {h_:+.3f} CI [{l_:+.3f},{u_:+.3f}] p {p_:.3f} (csv {cs.loc[k, 'd_sharpe_post2010']:+.3f}, p {cs.loc[k, 'p_d_sharpe_boot_post2010']:.3f}); "
          f"full dSR {hf:+.3f} p {pf:.3f} (csv p {cs.loc[k, 'p_d_sharpe_boot']:.3f})")
    if k in BLD:
        bd, blo, bhi, bp = BLD[k]
        chk("R1-9c", f"{k} post-2010 dSharpe", bd, h_, 0.0015, cs.loc[k, "d_sharpe_post2010"])
        if blo is not None:
            chk("R1-9c", f"{k} post-2010 CI lo (MC)", blo, l_, 0.03); chk("R1-9c", f"{k} post-2010 CI hi (MC)", bhi, u_, 0.03)
        chk("R1-9c", f"{k} post-2010 boot p (own seed, MC)", bp, p_, 0.03 if bp > 0.1 else 0.015)
    if k in ("A0X", "B0X"):
        chk("R1-9c", f"{k} full dSharpe", {"A0X": -0.010, "B0X": 0.001}[k], hf, 0.0015)
        chk("R1-9c", f"{k} full boot p (own seed, MC)", {"A0X": 0.73, "B0X": 0.98}[k], pf, 0.03)
    if k == "B5M":
        rr = nw(S(b_["net"] - bt["net"], "post2010"), X6)
        chk("R1-9c", "B5M post-2010 alpha diff (%)", -1.99, 1200 * rr["b"]["const"], 0.005); chk("R1-9c", "B5M post-2010 alpha diff t", -2.10, rr["t"]["const"], 0.005)
chk("R1-9c", "post-2010 screen dSharpe min |.|", 0.02, min(abs(v[0]) for v in post.values()), 0.005)
chk("R1-9c", "post-2010 screen dSharpe max |.|", 0.12, max(abs(v[0]) for v in post.values()), 0.005)
flag("R1-9c", "every screen below primary post-2010", all(v[0] < 0 for v in post.values()))
chk("R1-9c", "min post-2010 p among X screens (csv; own is MC)", 0.258, min(cs.loc[k, "p_d_sharpe_boot_post2010"] for k in SCR if k.endswith("X")), 0.0005,
    note=f"own seed min {min(post[k][3] for k in SCR if k.endswith('X')):.3f}")
chk("R1-9c", "full-sample max |dSharpe| across screens", 0.03, max(abs(v) for v in full_d.values()), 0.004)
chk("R1-9c", "full-sample min boot p across screens (own, MC)", 0.29, min(full_p.values()), 0.03)

# ============================== item 10 and 12c (builder 9, 11c): Short-Brown with UMD; attention lag
from team_pipeline import run_pipeline  # noqa: E402
tp0 = run_pipeline(bootstrap_reps=0, placebo_reps=0, macro_states=False, paired=False, extras=False)
tp1 = run_pipeline(attention=T["macro"]["attention"].shift(1), bootstrap_reps=0, placebo_reps=0, macro_states=False, paired=False, extras=False)
B = {("h3", 0): (0.038, 2.12, 1.10, -0.051, None, 0.07), ("h6", 0): (0.054, 2.59, 1.22, -0.061, None, 1.34),
     ("h3", 1): (0.037, 1.99, 1.27, -0.030, -1.19, 0.73), ("h6", 1): (0.057, 2.70, 1.50, -0.049, -1.92, 1.19)}
for (h, lag), (bi, ti, tiu, hml, thml, ret) in B.items():
    tp = tp0 if lag == 0 else tp1
    s_ = S(tp["strategies"][f"Original | Short Brown hold {h[1]}m"]["net_return"], "post2010")
    Xs = F.loc[s_.index]
    r3 = nw(s_, Xs[["Mkt-RF", "SMB", "HML"]]); ri = nw(s_, Xs[["Mkt-RF", "SMB", "HML", "INDMOM"]]); ru = nw(s_, Xs[["Mkt-RF", "SMB", "HML", "UMD"]])
    riu = nw(s_, Xs[["Mkt-RF", "SMB", "HML", "UMD", "INDMOM"]])
    tag = f"SB {h} lag{lag}"
    chk("R1-10", f"{tag} ann ret post-2010 (%)", ret, 1200 * s_.mean(), 0.005)
    chk("R1-10", f"{tag} INDMOM loading", bi, ri["b"]["INDMOM"], 0.0005); chk("R1-10", f"{tag} INDMOM t", ti, ri["t"]["INDMOM"], 0.005)
    chk("R1-10", f"{tag} INDMOM t with UMD", tiu, riu["t"]["INDMOM"], 0.005)
    chk("R1-10", f"{tag} FF3 HML", hml, r3["b"]["HML"], 0.0005)
    if thml is not None:
        chk("R1-10", f"{tag} FF3 HML t", thml, r3["t"]["HML"], 0.005)
    if lag == 0:
        chk("R1-10", f"{tag} % HML absorbed by UMD alone", 26, 100 * (1 - ru["b"]["HML"] / r3["b"]["HML"]), 0.5)
        c_ = nw(s_, INDMOM.loc[s_.index].to_frame())
        chk("R1-10", f"{tag} corr-regression NW t (corr t)", {"h3": 2.34, "h6": 2.79}[h], c_["t"]["INDMOM"], 0.01)

# ============================== other new/changed numbers
hg = S(GB, "holdout"); c1 = nw(hg, INDMOM.loc[hg.index].to_frame()); c2 = nw(hg, F5["UMD"].loc[hg.index].to_frame())
chk("other", "holdout corr(GB, INDMOM)", -0.29, hg.corr(INDMOM.loc[hg.index]), 0.005); chk("other", "holdout corr(GB, UMD)", -0.29, hg.corr(F5["UMD"].loc[hg.index]), 0.005)
chk("other", "holdout corr t (about -1.87)", -1.87, c1["t"]["INDMOM"], 0.02, note=f"UMD t {c2['t']['UMD']:.3f}")
nxt = R.shift(-1); ics = []
for t_ in Wh.index - pd.offsets.MonthEnd(1):
    win = R.loc[:t_].iloc[-12:-1]; s = (1 + win).prod(min_count=11) - 1; s[win.isna().any()] = np.nan
    m = s.notna() & nxt.loc[t_].notna(); ics.append(stats.spearmanr(s[m], nxt.loc[t_][m])[0])
ics = pd.Series(ics, index=Wh.index)
chk("other", "rank IC post-2010", 0.033, S(ics, "post2010").mean(), 0.0005); chk("other", "rank IC holdout t", 1.14, nw(S(ics, "holdout"))["t"]["const"], 0.005)

# ============================== item 11 (builder 10): ledger, own Holm/BH, survivors
led = tab("tests_ledger"); mt = tab("multiple_testing")
chk("R1-11", "ledger rows", 416, len(led), 0); chk("R1-11", "primaries", 4, int((led.primary_or_exploratory == "primary").sum()), 0)
flag("R1-11", "no duplicate test ids / NaN p", (not led.test_id.duplicated().any()) and (not led.p_value_two_sided.isna().any()))
isload = led.note.fillna("").str.startswith("[loading]")
chk("R1-11", "[loading] rows", 30, int(isload.sum()), 0)
def holm_own(p):
    o = np.argsort(p); m = len(p); adj = np.empty(m); run = 0
    for k, j in enumerate(o):
        run = max(run, (m - k) * p[j]); adj[j] = min(1, run)
    return adj
def bh_own(p):
    o = np.argsort(p); m = len(p); adj = np.empty(m); run = 1.0
    for k in range(m - 1, -1, -1):
        j = o[k]; run = min(run, p[j] * m / (k + 1)); adj[j] = run
    return adj
L = led.set_index("test_id"); pri = L[L.primary_or_exploratory == "primary"]; ex = L[L.primary_or_exploratory == "exploratory"]
hp = pd.Series(holm_own(pri.p_value_two_sided.values), index=pri.index)
bhp = pd.Series(bh_own(ex.p_value_two_sided.values), index=ex.index)
exn = ex[~ex.note.fillna("").str.startswith("[loading]")]; bhn = pd.Series(bh_own(exn.p_value_two_sided.values), index=exn.index)
M = mt.set_index("test_id")
chk("R1-11", "max |own Holm - csv|", 0, (hp - M.loc[hp.index, "p_holm_within_primary"]).abs().max(), 1e-12)
chk("R1-11", "max |own BH - csv|", 0, (bhp - M.loc[bhp.index, "p_bh_within_exploratory"]).abs().max(), 1e-12)
chk("R1-11", "max |own BH excl loadings - csv|", 0, (bhn - M.loc[bhn.index, "p_bh_exploratory_excl_loadings"]).abs().max(), 1e-12)
chk("R1-11", "Holm P1/P2/Q3", 0.823, hp[["M5-P1", "M5-P2", "M5-Q3-PRIMARY"]].max(), 0.0005); chk("R1-11", "Holm Q4", 0.211, hp["M5-Q4-PRIMARY"], 0.0005)
chk("R1-11", "BH<0.05 with loadings", 37, int((bhp < 0.05).sum()), 0); chk("R1-11", "BH<0.05 excl loadings", 26, int((bhn < 0.05).sum()), 0)
surv = set(bhp[bhp < 0.05].index); surv_n = set(bhn[bhn < 0.05].index); loads = set(L[isload.values].index)
flag("R1-11", "survivors excl loadings == survivors minus loadings", surv_n == surv - loads, f"{len(surv & loads)} loadings among 37")
cats = {"INDMOM-UMD corr": [i for i in surv_n if "corr-INDMOM-UMD" in i], "raw mean + CAPM/FF3/FF5 full": [i for i in surv_n if i in ("M5-Q1-mean-full_1970", "M5-Q1-alpha-CAPM-full_1970", "M5-Q1-alpha-FF3-full_1970", "M5-Q1-alpha-FF5-full_1970")],
        "rank IC full": [i for i in surv_n if i == "M5-Q3-IC-full_1970"], "optimizer full alphas": [i for i in surv_n if i.startswith("M5-Q3-optalpha-") and i.endswith("full_1970")],
        "DM BxM": [i for i in surv_n if "DM-BxM" in i], "COVID alphas": [i for i in surv_n if i.endswith("-covid")], "6-1 holdout": [i for i in surv_n if i == "M5-Q2-window_6-1-holdout"]}
exp_n = {"INDMOM-UMD corr": 4, "raw mean + CAPM/FF3/FF5 full": 4, "rank IC full": 1, "optimizer full alphas": 11, "DM BxM": 2, "COVID alphas": 3, "6-1 holdout": 1}
for k, v in cats.items():
    chk("R1-11", f"survivor category: {k}", exp_n[k], len(v), 0, note=",".join(sorted(v)) if k == "optimizer full alphas" else "")
flag("R1-11", "categories cover all 26", sum(len(v) for v in cats.values()) == len(surv_n))
for tid, b_ in {"M5-Q1-alpha-FF5+UMD-covid": 0.022, "M5-Q2-window_6-1-holdout": 0.029, "M5-Q3-optalpha-X_unc-2020s_to_2026_07": 0.220,
                "M5-Q3-optalpha-X_unc-post2010": 0.195, "M5-Q4-short_brown_h3-FF3+INDMOM-post2010": 0.205, "M5-Q4-short_brown_h6-FF3+INDMOM-post2010": 0.090,
                "M5-Q1-DM-BxM-momentum_net": 0.037, "M5-Q3-optalpha-X_unc-full_1970": 0.027}.items():
    if tid in bhp.index:
        chk("R1-11", f"BH p {tid}", b_, bhp[tid], 0.0005)
    else:
        flag("R1-11", f"BH p {tid}", False, "test id not in ledger")
for pat, b_ in {"screen-A5M": 0.195, "screen-B5M": 0.153}.items():
    ids = [i for i in bhp.index if pat in i and "post2010" in i and "dIR" in i]
    chk("R1-11", f"BH p {ids}", b_, bhp[ids[0]] if ids else np.nan, 0.0005)
ids = [i for i in bhp.index if "vs-primary" in i and "post2010" in i]
chk("R1-11", f"BH p {ids}", 0.417, bhp[ids[0]] if ids else np.nan, 0.0005)
ids = [i for i in bhp.index if "corr-short_brown" in i and "post2010" in i]
print("  corr SB ids:", ids, [round(bhp[i], 3) for i in ids])
for i, b_ in zip(sorted(ids), (0.160, 0.056)):
    chk("R1-11", f"BH p {i}", b_, bhp[i], 0.0005)
flag("R1-11", "DM BxM and gross (0 bp) alpha now logged", any("DM-BxM" in i for i in L.index) and any("cost0" in i or "gross" in i.lower() for i in L.index),
     ", ".join([i for i in L.index if "DM-BxM" in i or "cost0" in i]))

pd.DataFrame(rows).to_csv(OUT / "verify_round2_results.csv", index=False)
print("\nDISCREPANCIES:"); print(pd.DataFrame(rows).query("verdict == 'DISCREPANCY'")[["item", "claim", "builder", "mine", "note"]].to_string())
